# Generated by Django 4.2.7 on 2023-11-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("Day", "Day"), ("Night", "Night")],
                        default="Day",
                        help_text="Select the shift time: Day or Night",
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
