# Generated by Django 4.2.7 on 2023-11-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webrota_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user",
            field=models.CharField(
                choices=[
                    ("User_A", "User_A"),
                    ("User_B", "User_B"),
                    ("User_C", "User_C"),
                    ("User_D", "User_D"),
                ],
                default="User_A",
                help_text="Select user",
                max_length=100,
            ),
        ),
    ]
