# Generated by Django 4.2.7 on 2023-11-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webrota_app", "0003_alter_user_shift_alter_user_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Shifting",
        ),
    ]
